name: MARL
channels:
  - pytorch
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.1.31
  - filelock=3.13.1
  - freetype=2.12.1
  - gmpy2=2.1.2
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jpeg=9e
  - lcms2=2.16
  - lerc=4.0.0
  - libdeflate=1.22
  - libffi=3.4.4
  - libjpeg-turbo=2.0.0
  - libpng=1.6.39
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.0.16
  - pip=24.2
  - pybind11-abi=4
  - pysocks=1.7.1
  - python=3.11.8
  - pyyaml=6.0.2
  - requests=2.32.3
  - setuptools=75.1.0
  - sqlite=3.45.3
  - sympy=1.13.3
  - tbb=2021.8.0
  - tk=8.6.14
  - typing_extensions=4.12.2
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
prefix: /Users/ronchy2000/DevelopEnv/anaconda3/envs/MARL
